services:
  ollama:
    volumes:
      - ${OLLAMA_DATA_PATH:-./ollama/ollama}:/root/.ollama
    container_name: ${OLLAMA_CONTAINER_NAME:-ollama}
    pull_policy: ${OLLAMA_PULL_POLICY:-always}
    tty: true
    restart: ${OLLAMA_GPU_RESTART_POLICY:-unless-stopped}
    image: ${OLLAMA_NVIDIA_IMAGE:-ollama/ollama:latest}
    ports:
      - "${OLLAMA_PORT:-7869}:11434"
    environment:
      OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE:-15m}
      OLLAMA_HOST: ${OLLAMA_HOST:-0.0.0.0}
      OLLAMA_OPTS: ${OLLAMA_OPTS:---offload cpu}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
      # OLLAMA_MODELS: ${OLLAMA_MODELS:-/root/.ollama/models}
      # OLLAMA_NUM_PARALLEL: ${OLLAMA_NUM_PARALLEL:-1}
      # OLLAMA_MAX_LOADED_MODELS: ${OLLAMA_MAX_LOADED_MODELS:-1}
      # OLLAMA_LOAD_TIMEOUT: ${OLLAMA_LOAD_TIMEOUT:-5m}
      # OLLAMA_MAX_QUEUE: ${OLLAMA_MAX_QUEUE:-512}
      # OLLAMA_FLASH_ATTENTION: ${OLLAMA_FLASH_ATTENTION:-0}
      # OLLAMA_KV_CACHE_TYPE: ${OLLAMA_KV_CACHE_TYPE:-f16}
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${NVIDIA_GPU_COUNT:-1}
              # device_ids: ["${NVIDIA_GPU_DEVICE_ID:-0}"]
              capabilities: [gpu]
  ollama-webui:
    image: ${OPEN_WEBUI_GPU_IMAGE:-ghcr.io/open-webui/open-webui:latest}
    container_name: ${OPEN_WEBUI_CONTAINER_NAME:-ollama-webui}
    volumes:
      - ${OPEN_WEBUI_DATA_PATH:-./ollama/ollama-webui}:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "${OPEN_WEBUI_PORT:-8080}:8080"
    environment: 
      # https://docs.openwebui.com/reference/env-configuration
      OLLAMA_BASE_URLS: ${OPEN_WEBUI_OLLAMA_BASE_URLS:-http://host.docker.internal:7869} # semicolon-separated Ollama hosts
      ENV: ${OPEN_WEBUI_ENV:-dev}
      WEBUI_AUTH: ${OPEN_WEBUI_AUTH:-False}
      WEBUI_NAME: ${OPEN_WEBUI_NAME:-OpenWebUi}
      WEBUI_URL: ${OPEN_WEBUI_URL:-http://localhost:8080}
      WEBUI_SECRET_KEY: ${OPEN_WEBUI_SECRET_KEY:-t0p-s3cr3t}
      # ENABLE_OLLAMA_API: ${OPEN_WEBUI_ENABLE_OLLAMA_API:-True}
      # OLLAMA_BASE_URL: ${OPEN_WEBUI_OLLAMA_BASE_URL:-http://host.docker.internal:7869}
      # DEFAULT_MODELS: ${OPEN_WEBUI_DEFAULT_MODELS:-}
      # ENABLE_OPENAI_API: ${OPEN_WEBUI_ENABLE_OPENAI_API:-True}
      # OPENAI_API_BASE_URL: ${OPEN_WEBUI_OPENAI_API_BASE_URL:-https://api.openai.com/v1}
      # OPENAI_API_KEY: ${OPEN_WEBUI_OPENAI_API_KEY:-}
    extra_hosts:
      - ${OPEN_WEBUI_HOST_GATEWAY:-host.docker.internal:host-gateway}
    restart: ${OPEN_WEBUI_RESTART_POLICY:-unless-stopped}
    networks:
      - ollama-docker
      

networks:
  ollama-docker:
